"use client";
import { FormEvent, useEffect, useState } from "react";
type Device = { id: string; device_name: string; user_agent: string | null; last_seen_at: string };
export default function SecurityPage() {
  const [devices, setDevices] = useState<Device[]>([]); const [currentDeviceId, setCurrentDeviceId] = useState<string | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function load() { const response = await fetch("/api/customer/security"); const result = await response.json(); if (!response.ok) setError(result.error || "Unable to load devices"); else { setDevices(result.devices); setCurrentDeviceId(result.currentDeviceId); } }
  useEffect(() => { load(); }, []);
  async function changePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const response = await fetch("/api/customer/security", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ current_password: form.get("current_password"), new_password: form.get("new_password") }) }); const result = await response.json(); if (!response.ok) setError(result.error || "Unable to change password"); else setMessage(result.message); }
  async function revoke(deviceId: string) { const response = await fetch("/api/customer/security", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ device_id: deviceId }) }); const result = await response.json(); if (!response.ok) setError(result.error || "Unable to revoke device"); else { setMessage(deviceId === currentDeviceId ? "This device was signed out." : "Device revoked."); load(); } }
  return <div className="max-w-2xl space-y-5"><form onSubmit={changePassword} className="space-y-4 rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Change password</h2><input required name="current_password" type="password" placeholder="Current password" className="w-full rounded-lg border px-3 py-2" /><input required minLength={8} name="new_password" type="password" placeholder="New password (8+ characters)" className="w-full rounded-lg border px-3 py-2" /><button className="rounded-lg bg-slate-950 px-4 py-2 text-white">Change password</button></form><section className="rounded-xl border bg-white p-5"><h2 className="text-xl font-bold">Active devices</h2>{devices.map((device) => <div key={device.id} className="flex items-center justify-between gap-4 border-b py-4 text-sm"><span><b>{device.device_name}</b>{device.id === currentDeviceId && <em className="ml-2 text-emerald-600">Current</em>}<small className="block text-slate-400">Last active {new Date(device.last_seen_at).toLocaleString()}</small></span><button onClick={() => revoke(device.id)} className="text-red-600">Sign out</button></div>)}{!devices.length && <p className="mt-3 text-sm text-slate-500">No tracked devices yet.</p>}</section>{(error || message) && <p className={error ? "text-red-600" : "text-emerald-600"}>{error || message}</p>}</div>;
}
