"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import Toast from "@/components/admin/Toast";

interface Product { id: string; name: string; slug: string; description: string | null; price: number; compare_at_price: number | null; stock: number; reorder_threshold: number; barcode: string | null; images: string[]; category_id: string | null; is_active: boolean; categories?: { name: string } | null; product_variants?: ProductVariant[]; product_images?: { id: string; url: string }[] }
interface ProductVariant { id?: string; sku: string; barcode?: string | null; name: string; options: Record<string, string>; price: number | null; compare_at_price: number | null; stock: number; reorder_threshold?: number; is_active: boolean }
interface Category { id: string; name: string; slug: string; image_url: string | null; parent_id: string | null }
interface Order { id: string; tran_id: string; customer_name: string; customer_phone: string; total: number; payment_status: string; order_status: string; created_at: string }
interface DashboardData { products: Product[]; categories: Category[]; orders: Order[]; lowStock: Product[]; activity: { id: string; action: string; entity_type: string; created_at: string }[]; stats: { orderCount: number; revenue: number; productCount: number; lowStockCount: number } }

const blankProduct = { name: "", slug: "", description: "", price: "", compare_at_price: "", stock: "", reorder_threshold: "10", barcode: "", category_id: "", images: "", variants: "" };
const blankCategory = { name: "", slug: "", image_url: "" };

export default function AdminPage() {
  const [authenticated, setAuthenticated] = useState<boolean | null>(null);
  const [data, setData] = useState<DashboardData | null>(null);
  const [tab, setTab] = useState("Overview");
  const [query, setQuery] = useState("");
  const [product, setProduct] = useState<typeof blankProduct & { id?: string; previous_stock?: number }>(blankProduct);
  const [category, setCategory] = useState<typeof blankCategory & { id?: string }>(blankCategory);
  const [message, setMessage] = useState("");
  const [loginError, setLoginError] = useState("");
  const [loadError, setLoadError] = useState("");

  async function load() {
    const response = await fetch("/api/admin");
    if (response.status === 401) { setAuthenticated(false); return; }
    const result = await response.json().catch(() => ({}));
    if (!response.ok) {
      setAuthenticated(true);
      setLoadError(result.error || "Could not load admin data. Check the database and service-role key.");
      return;
    }
    setLoadError("");
    setAuthenticated(true);
    setData({
      products: Array.isArray(result.products) ? result.products : [],
      categories: Array.isArray(result.categories) ? result.categories : [],
      orders: Array.isArray(result.orders) ? result.orders : [],
      lowStock: Array.isArray(result.lowStock) ? result.lowStock : [],
      activity: Array.isArray(result.activity) ? result.activity : [],
      stats: result.stats || { orderCount: 0, revenue: 0, productCount: 0, lowStockCount: 0 },
    });
  }
  useEffect(() => { load(); }, []);

  async function login(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoginError("");
    const form = new FormData(event.currentTarget);
    const response = await fetch("/api/admin/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) });
    if (!response.ok) { setLoginError("Invalid email or password"); return; }
    await load();
  }
  async function logout() { await fetch("/api/admin/auth", { method: "DELETE" }); setAuthenticated(false); setData(null); }
  async function action(body: unknown) {
    setMessage("");
    const response = await fetch("/api/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    const result = await response.json();
    if (!response.ok) { setMessage(result.error || "Action failed"); return; }
    setMessage("Saved successfully"); await load();
  }
  async function saveProduct(event: FormEvent) {
    event.preventDefault();
    let variants: unknown[] = [];
    try { variants = product.variants.trim() ? JSON.parse(product.variants) : []; } catch { setMessage("Variants must be valid JSON"); return; }
    if (!Array.isArray(variants)) { setMessage("Variants must be a JSON array"); return; }
    await action({ action: "save_product", product: { ...product, price: Number(product.price), compare_at_price: product.compare_at_price ? Number(product.compare_at_price) : null, stock: Number(product.stock), reorder_threshold: Number(product.reorder_threshold), images: product.images.split("\n").map((image) => image.trim()).filter(Boolean), variants } });
    setProduct(blankProduct);
  }
  async function saveCategory(event: FormEvent) {
    event.preventDefault(); await action({ action: "save_category", category }); setCategory(blankCategory);
  }
  const filteredProducts = useMemo(() => data?.products.filter((item) => `${item.name} ${item.slug}`.toLowerCase().includes(query.toLowerCase())) || [], [data, query]);

  if (authenticated === null) return <div className="min-h-screen grid place-items-center bg-slate-950 text-white">Loading admin console...</div>;
  if (!authenticated) return <main className="min-h-screen grid place-items-center bg-slate-950 px-4"><form onSubmit={login} className="w-full max-w-md bg-white rounded-2xl p-8 text-slate-900 shadow-2xl"><p className="text-xs uppercase tracking-[0.3em] text-orange-600 font-bold">MyShopBD / Control room</p><h1 className="text-3xl font-bold mt-3">Welcome back</h1><p className="text-slate-500 mt-2 mb-7">Sign in to manage your store.</p><label className="text-sm font-semibold">Admin email<input name="email" type="email" required className="mt-2 mb-4 w-full border rounded-lg px-3 py-3" /></label><label className="text-sm font-semibold">Password<input name="password" type="password" required className="mt-2 mb-5 w-full border rounded-lg px-3 py-3" /></label>{loginError && <p className="text-red-600 text-sm mb-4">{loginError}</p>}<button className="w-full rounded-lg bg-slate-950 text-white py-3 font-semibold">Sign in</button></form></main>;
  if (loadError) return <main className="min-h-screen grid place-items-center bg-[#f4f6f8] px-4"><div className="max-w-xl bg-white border rounded-xl p-6"><h1 className="text-xl font-bold">Dashboard data could not load</h1><p className="text-red-600 mt-3 text-sm">{loadError}</p><button onClick={load} className="mt-5 rounded-lg bg-orange-500 text-white px-4 py-2 text-sm font-semibold">Retry</button></div></main>;
  if (!data) return <div className="p-10">Could not load dashboard.</div>;

  return <div className="min-h-screen bg-[#f4f6f8] text-slate-900"><aside className="fixed inset-y-0 left-0 hidden w-64 bg-slate-950 text-white p-6 lg:block"><div className="text-xl font-bold">MyShop<span className="text-orange-500">BD</span></div><p className="text-slate-500 text-xs mt-1">Store operations</p><nav className="mt-12 space-y-2">{["Overview", "Products", "Orders", "Categories"].map((item) => <button key={item} onClick={() => setTab(item)} className={`w-full text-left rounded-lg px-4 py-3 text-sm ${tab === item ? "bg-orange-500 text-white" : "text-slate-300 hover:bg-slate-800"}`}>{item}</button>)}</nav><button onClick={logout} className="absolute bottom-8 text-sm text-slate-400 hover:text-white">Sign out</button></aside><main className="lg:ml-64 p-5 md:p-8 max-w-[1600px]"><header className="flex flex-wrap gap-4 justify-between items-center mb-8"><div><p className="text-xs uppercase tracking-[0.25em] text-orange-600 font-bold">Tuesday, September 3</p><h1 className="text-3xl font-bold mt-1">{tab}</h1></div><div className="flex gap-3"><button onClick={load} className="border bg-white rounded-lg px-4 py-2 text-sm">Refresh</button><button onClick={logout} className="lg:hidden border bg-white rounded-lg px-4 py-2 text-sm">Sign out</button></div></header>{message && <p className="mb-4 rounded-lg bg-emerald-50 text-emerald-700 px-4 py-3 text-sm">{message}</p>}{tab === "Overview" && <Overview data={data} setTab={setTab} />}{tab === "Products" && <Products data={data} query={query} setQuery={setQuery} product={product} setProduct={setProduct} saveProduct={saveProduct} action={action} />}{tab === "Categories" && <Categories data={data} category={category} setCategory={setCategory} saveCategory={saveCategory} />}{tab === "Orders" && <Orders data={data} action={action} />}</main></div>;
}

function Overview({ data, setTab }: { data: DashboardData; setTab: (tab: string) => void }) { return <><section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{[["Gross revenue", `৳${data.stats.revenue.toLocaleString()}`, "Paid orders"], ["Total orders", data.stats.orderCount, "All time"], ["Live products", data.stats.productCount, "Catalog"], ["Low stock", data.stats.lowStockCount, "10 units or less"]].map(([label, value, note]) => <div key={label} className="bg-white border rounded-xl p-5"><p className="text-sm text-slate-500">{label}</p><p className="text-3xl font-bold mt-3">{value}</p><p className="text-xs text-slate-400 mt-2">{note}</p></div>)}</section><section className="grid xl:grid-cols-[1.4fr_1fr] gap-5 mt-5"><div className="bg-white border rounded-xl p-5"><div className="flex justify-between items-center mb-4"><h2 className="font-bold text-lg">Recent orders</h2><button onClick={() => setTab("Orders")} className="text-orange-600 text-sm font-semibold">View all</button></div><OrderTable orders={data.orders.slice(0, 6)} action={async () => {}} /></div><div className="bg-slate-950 text-white rounded-xl p-5"><h2 className="font-bold text-lg">Stock watch</h2><div className="mt-4 space-y-3">{data.lowStock.slice(0, 6).map((item) => <div key={item.id} className="flex justify-between border-b border-slate-800 pb-3"><span className="text-sm truncate pr-3">{item.name}</span><span className={item.stock === 0 ? "text-red-400" : "text-orange-400"}>{item.stock} left</span></div>)}{!data.lowStock.length && <p className="text-slate-400 text-sm">Inventory is healthy.</p>}</div></div></section></> }

function Products({ data, query, setQuery, product, setProduct, saveProduct, action }: { data: DashboardData; query: string; setQuery: (value: string) => void; product: any; setProduct: (value: any) => void; saveProduct: (event: FormEvent) => void; action: (body: unknown) => Promise<void> }) { const filteredProducts = data.products.filter((item) => `${item.name} ${item.slug}`.toLowerCase().includes(query.toLowerCase())); return <div className="grid xl:grid-cols-[1fr_390px] gap-5"><section className="bg-white border rounded-xl overflow-hidden"><div className="p-5 border-b flex flex-wrap gap-3 justify-between"><div><h2 className="font-bold text-lg">Product catalog</h2><p className="text-sm text-slate-500">{data.products.length} products</p></div><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products..." className="border rounded-lg px-3 py-2 text-sm" /></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Product</th><th className="p-4">Category</th><th className="p-4">Price</th><th className="p-4">Variants</th><th className="p-4">Stock</th><th className="p-4">Status</th><th /></tr></thead><tbody>{query && !filteredProducts.length ? <tr><td colSpan={7} className="p-8 text-center">No products found.</td></tr> : filteredProducts.map((item) => <tr key={item.id} className="border-t"><td className="p-4 font-medium">{item.name}<span className="block text-xs text-slate-400">/{item.slug}</span></td><td className="p-4 text-slate-500">{item.categories?.name || "Unassigned"}</td><td className="p-4">৳{item.price}</td><td className="p-4">{item.product_variants?.length || 0}</td><td className={`p-4 font-semibold ${item.stock <= 10 ? "text-orange-600" : ""}`}>{item.stock}</td><td className="p-4"><span className={`text-xs px-2 py-1 rounded-full ${item.is_active ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{item.is_active ? "Live" : "Archived"}</span></td><td className="p-4 text-right"><button onClick={() => setProduct({ ...item, images: item.images.join("\n"), variants: JSON.stringify(item.product_variants || [], null, 2), price: String(item.price), compare_at_price: item.compare_at_price ? String(item.compare_at_price) : "", stock: String(item.stock), description: item.description || "", category_id: item.category_id || "", previous_stock: item.stock })} className="text-orange-600 font-semibold">Edit</button></td></tr>)}</tbody></table></div></section><ProductForm product={product} setProduct={setProduct} categories={data.categories} saveProduct={saveProduct} /></div> }

function ProductForm({ product, setProduct, categories, saveProduct }: { product: any; setProduct: (value: any) => void; categories: Category[]; saveProduct: (event: FormEvent) => void }) { const update = (key: string, value: string) => setProduct({ ...product, [key]: value }); return <form onSubmit={saveProduct} className="bg-white border rounded-xl p-5 h-fit space-y-3"><div className="flex justify-between"><h2 className="font-bold">{product.id ? "Edit product" : "Add product"}</h2>{product.id && <button type="button" onClick={() => setProduct(blankProduct)} className="text-xs text-slate-500">Clear</button>}</div>{[["name", "Product name"], ["slug", "Slug"], ["price", "Price"], ["compare_at_price", "Compare-at price"], ["stock", "Stock"]].map(([key, label]) => <label key={key} className="block text-sm font-medium">{label}<input required={key !== "compare_at_price"} type={key === "price" || key === "compare_at_price" || key === "stock" ? "number" : "text"} value={product[key]} onChange={(event) => update(key, event.target.value)} className="mt-1 w-full border rounded-lg px-3 py-2" /></label>)}<label className="block text-sm font-medium">Category<select value={product.category_id} onChange={(event) => update("category_id", event.target.value)} className="mt-1 w-full border rounded-lg px-3 py-2"><option value="">Unassigned</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm font-medium">Description<textarea value={product.description} onChange={(event) => update("description", event.target.value)} rows={3} className="mt-1 w-full border rounded-lg px-3 py-2" /></label><label className="block text-sm font-medium">Image URLs <span className="font-normal text-slate-400">one per line</span><textarea value={product.images} onChange={(event) => update("images", event.target.value)} rows={2} className="mt-1 w-full border rounded-lg px-3 py-2" /></label><label className="block text-sm font-medium">Variants JSON <span className="font-normal text-slate-400">SKU, name, options, price, stock</span><textarea value={product.variants} onChange={(event) => update("variants", event.target.value)} rows={5} placeholder='[{"sku":"TIMER-RED","name":"Red","options":{"color":"red"},"price":1490,"stock":10}]' className="mt-1 w-full border rounded-lg px-3 py-2 font-mono text-xs" /></label><button className="w-full bg-orange-500 hover:bg-orange-600 text-white rounded-lg py-3 font-semibold">Save product</button></form> }

function Categories({ data, category, setCategory, saveCategory }: { data: DashboardData; category: any; setCategory: (value: any) => void; saveCategory: (event: FormEvent) => void }) { return <div className="grid lg:grid-cols-[1fr_390px] gap-5"><section className="bg-white border rounded-xl p-5"><h2 className="font-bold text-lg mb-4">Categories</h2><div className="divide-y">{data.categories.map((item) => <div key={item.id} className="py-4 flex justify-between"><div><p className="font-semibold">{item.name}</p><p className="text-xs text-slate-400">/{item.slug}</p></div><button onClick={() => setCategory(item)} className="text-orange-600 text-sm font-semibold">Edit</button></div>)}</div></section><form onSubmit={saveCategory} className="bg-white border rounded-xl p-5 h-fit space-y-4"><h2 className="font-bold">{category.id ? "Edit category" : "Add category"}</h2><label className="block text-sm font-medium">Name<input required value={category.name} onChange={(event) => setCategory({ ...category, name: event.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2" /></label><label className="block text-sm font-medium">Slug<input required value={category.slug} onChange={(event) => setCategory({ ...category, slug: event.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2" /></label><label className="block text-sm font-medium">Image URL<input value={category.image_url} onChange={(event) => setCategory({ ...category, image_url: event.target.value })} className="mt-1 w-full border rounded-lg px-3 py-2" /></label><button className="w-full bg-orange-500 text-white rounded-lg py-3 font-semibold">Save category</button></form></div> }

function Orders({ data, action }: { data: DashboardData; action: (body: unknown) => Promise<void> }) { return <section className="bg-white border rounded-xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold text-lg">Order management</h2><p className="text-sm text-slate-500">Update fulfillment and payment statuses.</p></div><OrderTable orders={data.orders} action={action} /></section> }
function OrderTable({ orders, action }: { orders: Order[]; action: (body: unknown) => Promise<void> }) { return <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-4">Order</th><th className="p-4">Customer</th><th className="p-4">Total</th><th className="p-4">Payment</th><th className="p-4">Fulfillment</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-t"><td className="p-4 font-semibold">{order.tran_id}<span className="block text-xs text-slate-400">{new Date(order.created_at).toLocaleDateString()}</span></td><td className="p-4">{order.customer_name}<span className="block text-xs text-slate-400">{order.customer_phone}</span></td><td className="p-4">৳{order.total}</td><td className="p-4"><select value={order.payment_status} onChange={(event) => action({ action: "update_order", id: order.id, payment_status: event.target.value })} className="border rounded px-2 py-1 text-xs"><option>pending</option><option>paid</option><option>failed</option><option>cancelled</option></select></td><td className="p-4"><select value={order.order_status} onChange={(event) => action({ action: "update_order", id: order.id, order_status: event.target.value })} className="border rounded px-2 py-1 text-xs"><option>processing</option><option>shipped</option><option>delivered</option><option>cancelled</option></select></td></tr>)}</tbody></table>{!orders.length && <p className="p-8 text-center text-slate-500">No orders yet.</p>}</div> }
