"use client";
import { useEffect, useState } from "react";
type Order = { id: string; tran_id: string; total: number; order_status: string; payment_status: string; created_at: string; items: { product_name: string; quantity: number; unit_price: number }[]; timeline: { status: string; created_at: string }[] };
export default function AccountOrdersPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [filter, setFilter] = useState("all"); const [open, setOpen] = useState<string | null>(null); const [error, setError] = useState("");
  useEffect(() => { fetch("/api/customer/orders").then(async (response) => { const result = await response.json(); if (!response.ok) setError(result.error || "Unable to load orders"); else setOrders(result.orders || []); }); }, []);
  const filtered = orders.filter((order) => filter === "all" || order.order_status === filter);
  return <section className="rounded-xl border bg-white p-5"><div className="flex flex-wrap gap-2 border-b pb-4">{[["all", "All"], ["processing", "Processing"], ["shipped", "Shipped"], ["delivered", "Delivered"], ["cancelled", "Cancelled/Returned"]].map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-lg px-3 py-2 text-sm ${filter === value ? "bg-orange-500 text-white" : "bg-slate-100"}`}>{label}</button>)}</div>{error && <p className="py-5 text-sm text-red-600">{error}</p>}{filtered.map((order) => <article key={order.id} className="border-b py-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{order.tran_id}</p><p className="text-sm text-slate-500">{new Date(order.created_at).toLocaleDateString()} · {order.order_status}</p></div><div className="text-right"><p className="font-bold">৳{order.total}</p><button onClick={() => setOpen(open === order.id ? null : order.id)} className="text-sm text-orange-600">{open === order.id ? "Hide details" : "View details"}</button></div></div>{open === order.id && <div className="mt-4 rounded-lg bg-slate-50 p-4 text-sm"><p className="mb-2 font-semibold">Items</p>{order.items.map((item, index) => <p key={`${item.product_name}-${index}`}>{item.product_name} × {item.quantity} · ৳{item.unit_price}</p>)}<p className="mb-2 mt-4 font-semibold">Status timeline</p>{order.timeline.map((entry, index) => <p key={`${entry.status}-${index}`}>{entry.status} · {new Date(entry.created_at).toLocaleString()}</p>)}<a href={`/account/orders/${order.id}/invoice`} className="mt-3 inline-block text-orange-600">Download invoice</a></div>}</article>)}{!error && !filtered.length && <p className="py-8 text-center text-sm text-slate-500">No orders in this category.</p>}</section>;
}
