"use client";

import { useEffect, useState } from "react";

type InvoiceData = { order: { tran_id: string; invoice_number: string | null; customer_name: string; customer_phone: string; customer_email: string | null; shipping_address: string; shipping_city: string; subtotal: number; shipping_fee: number; total: number; created_at: string }; items: { product_name: string; unit_price: number; quantity: number }[] };

export default function InvoicePage({ params }: { params: Promise<{ id: string }> }) {
  const [data, setData] = useState<InvoiceData | null>(null); const [error, setError] = useState("");
  useEffect(() => { params.then(({ id }) => fetch(`/api/admin/orders/${id}`).then(async (response) => { const result = await response.json(); if (!response.ok) setError(result.error || "Unable to load invoice"); else setData(result); })); }, [params]);
  if (error) return <main className="p-8 text-red-600">{error}</main>;
  if (!data) return <main className="p-8">Loading invoice...</main>;
  const { order } = data;
  return <main className="min-h-screen bg-slate-100 p-5 md:p-10 print:bg-white print:p-0"><div className="max-w-3xl mx-auto bg-white p-8 md:p-12 print:max-w-none"><header className="flex justify-between border-b pb-8"><div><p className="text-orange-600 font-bold tracking-widest text-sm">MYSHOPBD</p><h1 className="text-3xl font-bold mt-2">Invoice</h1><p className="text-slate-500 mt-2">{order.invoice_number || order.tran_id}</p></div><div className="text-right text-sm text-slate-500"><p>{new Date(order.created_at).toLocaleDateString()}</p><p>Dhaka, Bangladesh</p></div></header><section className="grid sm:grid-cols-2 gap-6 py-8"><div><p className="text-xs uppercase tracking-wider text-slate-400">Bill to</p><p className="font-semibold mt-2">{order.customer_name}</p><p>{order.customer_phone}</p><p>{order.customer_email}</p></div><div><p className="text-xs uppercase tracking-wider text-slate-400">Ship to</p><p className="mt-2">{order.shipping_address}</p><p>{order.shipping_city}</p></div></section><table className="w-full text-sm"><thead className="border-y text-left"><tr><th className="py-3">Item</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Price</th><th className="py-3 text-right">Amount</th></tr></thead><tbody>{data.items.map((item, index) => <tr key={`${item.product_name}-${index}`} className="border-b"><td className="py-4">{item.product_name}</td><td className="py-4 text-right">{item.quantity}</td><td className="py-4 text-right">৳{item.unit_price}</td><td className="py-4 text-right">৳{Number(item.unit_price) * item.quantity}</td></tr>)}</tbody></table><div className="ml-auto max-w-xs space-y-2 py-6 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>৳{order.subtotal}</span></div><div className="flex justify-between"><span>Shipping</span><span>৳{order.shipping_fee}</span></div><div className="flex justify-between border-t pt-3 font-bold text-lg"><span>Total</span><span>৳{order.total}</span></div></div><footer className="border-t pt-6 text-sm text-slate-500">Thank you for shopping with MyShopBD.</footer><button onClick={() => window.print()} className="mt-8 bg-slate-950 text-white rounded-lg px-5 py-3 print:hidden">Print invoice</button></div></main>;
}
