import { NextRequest, NextResponse } from "next/server";
import { getCustomerSession } from "@/lib/customer-auth";
import { supabaseAdmin } from "@/lib/supabase";

async function auth() { return getCustomerSession(); }
export async function GET() { const session = await auth(); if (!session) return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const { data, error } = await supabaseAdmin().from("customer_addresses").select("*").eq("user_id", session.user.id).order("is_default", { ascending: false }).order("created_at", { ascending: false }); if (error) return NextResponse.json({ error: error.message }, { status: 500 }); return NextResponse.json({ addresses: data || [] }); }

export async function POST(req: NextRequest) { const session = await auth(); if (!session) return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const body = await req.json().catch(() => ({})); const address = { user_id: session.user.id, label: body.label === "Work" ? "Work" : "Home", recipient_name: String(body.recipient_name || "").trim(), phone: String(body.phone || "").trim(), full_address: String(body.full_address || "").trim(), city: String(body.city || "").trim(), zone: String(body.zone || "").trim() || null, is_default: Boolean(body.is_default) }; if (!address.recipient_name || !address.phone || !address.full_address || !address.city) return NextResponse.json({ error: "Complete address details are required" }, { status: 400 }); const supabase = supabaseAdmin(); if (address.is_default) await supabase.from("customer_addresses").update({ is_default: false }).eq("user_id", session.user.id); const { data, error } = await supabase.from("customer_addresses").insert(address).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json({ address: data }); }

export async function PUT(req: NextRequest) { const session = await auth(); if (!session) return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const body = await req.json().catch(() => ({})); const id = String(body.id || ""); if (!id) return NextResponse.json({ error: "Address ID is required" }, { status: 400 }); const updates = { label: body.label === "Work" ? "Work" : "Home", recipient_name: String(body.recipient_name || "").trim(), phone: String(body.phone || "").trim(), full_address: String(body.full_address || "").trim(), city: String(body.city || "").trim(), zone: String(body.zone || "").trim() || null, is_default: Boolean(body.is_default), updated_at: new Date().toISOString() }; const supabase = supabaseAdmin(); if (updates.is_default) await supabase.from("customer_addresses").update({ is_default: false }).eq("user_id", session.user.id).neq("id", id); const { data, error } = await supabase.from("customer_addresses").update(updates).eq("id", id).eq("user_id", session.user.id).select().single(); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json({ address: data }); }

export async function DELETE(req: NextRequest) { const session = await auth(); if (!session) return NextResponse.json({ error: "Authentication required" }, { status: 401 }); const id = req.nextUrl.searchParams.get("id"); if (!id) return NextResponse.json({ error: "Address ID is required" }, { status: 400 }); const { error } = await supabaseAdmin().from("customer_addresses").delete().eq("id", id).eq("user_id", session.user.id); if (error) return NextResponse.json({ error: error.message }, { status: 400 }); return NextResponse.json({ ok: true }); }
